### ISSUE TITLE
Getting Error when jest config is in package.json

### ISSUE THREAD

**Issue by ruanyl** [khanghoang/coc-jest#10]
Hi, thanks for the plugin, but I'm getting the following error when I start my editor, I don't have `jest.config.js` but have the config in `package.json`,
```
[coc.nvim] Error on active extension coc-inline-jest: TypeError: Path must be a string. Received null
```

**Comment by khanghoang** [comment]
hey @ruanyl, thanks for reporting this. I noticed the issue and will address it this weekend.

**Comment by khanghoang** [comment]
Addressed by https://github.com/khanghoang/coc-jest/commit/d4cac3fdd7af7f8c71d9e3acb409ce65e33f4cf3
